### ISSUE TITLE
2016-11-02

### ISSUE THREAD

**Issue by gustafsoldan** [4350/grandslam#40]
![image](https://cloud.githubusercontent.com/assets/11066719/19923603/810f8424-a0e8-11e6-8986-a4bce3ac342f.png)

**Comment by victorandree** [comment]
Two (three with explanatory) sets of graphs:
- [ ] What is threshold correlation?
- [ ] Residual threshold correlations
- [ ] Residuals with copula models

For writing today:
- What is threshold correlation?
  - Measure of tail dependency; how dependency changes as you move to extremes of the distribution. Between two normal distributed variables you expect /\-shape (for positively correlated variables).
  - Correlation for subset of data, shrinking quadrants
- Threshold correlations of GARCH residuals.
  - Why residuals? Because GARCH filters whatever it can capture, remaining is what GARCH essentially cannot model.
  - The presence of threshold correlations in GARCH residuals is evidence that they are not independent of each other (that's not a particularly deep insight in itself tho).
  - Threshold correlations are never on the unconditional correlation line, i.e. conditional on being in the quadrant, assuming you're operating under such and such correlation is wrong.
  - Concrete example: Mkt.RF-HML. If you're in a week when both are within their 25% worst, the correlation is most certainly not -0.30, but actually positive.
  - We want a model that can capture this; you care about what happens in the extremes.
  - Asymmetry in threshold correlations: What do we see? CMA-Mom displays asymmetry, although not very strong, reflecting higher downside risk than anticipated. RMW-HML and RMW-CMA too. Correlations are not constant as you move to the edges.
  - CMA-HML remains very high, flat and symmetric by comparison. All others have negative or close to zero unconditional, whereas CMA-HML is above 0.50. That's very high!
  - Extreme positive very different to extreme negative
  - Why residuals? Because that's what the copula is modeling
- Copula vs GARCH residuals
  - Can constant capture?
    - Not great to be honest.
    - Absolutely no overlap -- expect there note to be. More uncertainty the further out you go.
    - These models can capture some of the patterns seen in the data.
    - Student's t appears to be improvement over Gaussian copula.
    - We do have some asymmetry.
    - However, still not flexible enough to capture the very strong asymmetries seen between some pairs. Not enough to capture e.g. RMW-HML or RMW-CMA.
    - Limitation of the parsimonious model
